paswoord
uit91258

In [5]:
import numpy as np

In [8]:
a = np.arange(27).reshape(3,3,3,)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
# 4 pictures resulotion 8x8
a = np.arange(4*8*8).reshape(4,8,8)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [23]:
np.random.randint(0,255,(10,8,8))


array([[[ 56,  86,  15,  24, 194, 208,  64, 181],
        [178,   1, 191, 172, 145, 246, 107,  75],
        [ 70,  12, 254, 215, 130,  85, 240,  22],
        [ 40, 241, 167, 251, 235,  62,  57,  22],
        [ 30,  82,  17,  73, 215,  46, 141, 110],
        [119, 222, 192, 150, 152, 219,  37,  78],
        [  5, 193, 131, 194, 108, 162,  38, 244],
        [ 87, 220,  33, 140, 117, 223, 197, 206]],

       [[126,  61,  38, 155,  25, 251,  75, 205],
        [  6, 156, 107, 125, 134, 151, 185, 167],
        [200,  63, 125, 116, 129, 215, 160, 168],
        [230,   4,  83, 176,  73, 163, 208, 182],
        [222, 121,  21,  86, 138, 108,  93,  90],
        [ 90, 199, 229, 249, 162, 230, 135, 211],
        [ 48, 223, 224, 169,  69, 157, 162,  27],
        [ 28, 112,  96,  56, 173,  25, 137, 149]],

       [[185,  82,  38, 187, 150, 117, 151,  42],
        [ 87, 133, 142, 138, 187, 222,  14, 212],
        [127, 224, 119, 198, 146,  85, 197, 171],
        [209,  13,  41, 236, 196, 145, 182, 10

In [13]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [14]:
print(a.ndim) #number of dimention
print(a.shape) #number of axis in each dimention
print(a.size) # number of elements


2
(10, 10)
100


In [24]:
a = np.array[[1,2,3],
            [4,5,6]]

TypeError: 'builtin_function_or_method' object is not subscriptable